---
apiVersion: v1
kind: Secret
metadata:
  name: podinfo-auth
  namespace: flux-system
stringData:
  githubAppID: "1"
  githubAppInstallationID: "2"
  githubAppPrivateKey: |
    -----BEGIN RSA PRIVATE KEY-----
    .....
    -----END RSA PRIVATE KEY-----
type: Opaque

